version: '2'

services:

  broker:
    build: ./vopen-broker/broker/
    hostname: vopen-broker
    links:
      - "auth"
    ports:
      - 0.0.0.0:1883:1883   # mqtt port
      - 0.0.0.0:15675:15675 # web mqtt port
    environment:
      RABBITMQ_ERLANG_COOKIE: <erlang-cookie>

  auth:
    build: ./vopen-broker/auth/
    links:
      - "usersdb"
    volumes: # for development purposes
      - ./vopen-broker/auth/app.js:/usr/app/app.js
      - ./vopen-broker/auth/db.js:/usr/app/db.js

  usersdb:
    image: mongo:latest
